services:
  - type: web
    name: ecommerce_api
    runtime: ruby
    plan: free
    buildCommand: 'bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate'
    startCommand: './bin/rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
databases:
  - name: ecommerce-db
    plan: free